# Generated by Django 4.2 on 2024-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('P', 'PLANTA'), ('F', 'FUEGO'), ('A', 'AGUA'), ('T', 'TIERRA'), ('E', 'ELECTRICO')], max_length=30)),
                ('weigth', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('heigth', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
    ]
