# Generated by Django 4.2 on 2024-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'TIERRA'), ('F', 'FUEGO'), ('P', 'PLANTA'), ('E', 'ELECTRICO'), ('A', 'AGUA')], max_length=30),
        ),
    ]
