# Generated by Django 4.2 on 2024-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='heigth',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra'), ('P', 'Planta'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
